version: "3.9"

services:
  api:
    build:
      # Dockerfile for Flask app lives in ../../backend
      context: ../../backend
      dockerfile: Dockerfile
    container_name: chatbot-api
    env_file:
      - ../../backend/.env      # DB/Redis config for Flask
    depends_on:
      - db
      - redis
    networks:
      - app-net
    restart: unless-stopped # Reruns service if server is restarted

  db:
    image: postgres
    container_name: chatbot-postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}   # Renaming database to env-var: POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - app-net
    restart: unless-stopped

  redis:
    image: redis
    container_name: chatbot-redis
    volumes:
      - redis-data:/data
    networks:
      - app-net
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: chatbot-nginx
    ports:
      - "80:80"              # hit http://localhost/
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-net
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  app-net:
